stages:
  - build
  - style
  - test

build_job:
  stage: build
  script:
    - cd src/part2/cat/ && make && cd ..
    - cd grep/ && make && cd ../../..
  artifacts:
    paths:
      - src/part2/cat/
      - src/part2/grep/
    expire_in: 30 days

style_job:
  stage: style
  script:
    - clang-format -n -style=Google -Werror src/part2/cat/*.c src/part2/grep/*.h src/part2/grep/*.c

test_job:
  stage: test
  script:
    - ./src/cat/tests2.sh
    - ./src/grep/tests1.sh