stages:
  - build
  - style
  - test
  - deploy

build_job:
  stage: build
  script:
    - cd src/part2/cat/ && make && cd ..
    - cd grep/ && make && cd ../../..
  artifacts:
    paths:
      - src/part2/cat/
      - src/part2/grep/
    expire_in: 30 days

style_job:
  stage: style
  script:
    - clang-format -n -style=Google -Werror src/part2/cat/*.c src/part2/grep/*.h src/part2/grep/*.c

test_job:
  stage: test
  script:
    - cd src/part2/cat/ && make test && cd ..
    - cd grep/ && make test

deploy_job:
  stage: deploy
  script:
    - ssh-keyscan -H 10.10.0.2 >> ~/.ssh/known_hosts
    - ./src/ssh.sh
  when: manual
